d = int(input('Digite um número para ver sua tabuada:'))
print('--------------')
print('{} x 1 = {}'.format(d, d*1))
print('{} x 2 = {}'.format(d, d*2))
print('{} x 3 = {}'.format(d, d*3))
print('{} x 4 = {}'.format(d, d*4))
print('{} x 5 = {}'.format(d, d*5))
print('{} x 6 = {}'.format(d, d*6))
print('{} x 7 = {}'.format(d, d*7))
print('{} x 8 = {}'.format(d, d*8))
print('{} x 9 = {}'.format(d, d*9))
print('{} x 10 = {}'.format(d, d*10))
print('--------------')
