n = str(input('Digite seu nome completo:'))
print('Analisando seu nome...')
print('Seu nome em letra maiúscula é {}'.format(n.upper()))
print('Seu nome em letra minúscula é {}'.format(n.lower()))
print('Seu nome tem ao todo {} letras'.format(len(n) - n.count(' ')))
print('Seu primeiro nome tem {} letras'.format(n.find(' ')))
